### ISSUE TITLE
Trying English to Indonesian doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [botbahlul/java-vosk-livesubtitle#1]
I have tried it out in Japanese to Indonesian and it have worked fine, but when trying out English to Indonesian no text seem to get taken at all.

My Folder Structure for the Exe
C:\Folder\Class\IIP\pap2ref\Subtitle\java-vosk-livesubtitle-main\build\distributions\java-vosk-livesubtitle-main\lib\models
![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/70886947/94e6ad3c-2d96-41d7-872b-529f5548e23d)

Image of Japanese to Indonesian Working for Me
![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/70886947/08d25b70-04c4-4450-907c-3b22e20d9b53)

Image of English to Indonesian not working at all
![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/70886947/d892c86b-e829-4dbc-900b-0562408c6d60)

Can it be said it's because of English Language does not have a model?

**Comment by botbahlul** [comment]
I've included English model on that zip file, did you accidentally delete it ?
Other 20 languages supported by vosk will be downloaded into that 'models' folder when you click download model button.
You can also manually download those language models from https://alphacephei.com/vosk/models
All models I used in my app are 'small' models category.
If you understand java code, you can see in source code that I download them and then RENAME those zip extracted models to ISO-639-1 standard code.

![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/88623122/c986f243-6fb9-4b0c-97f5-a377ed652c0e)

![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/88623122/121b3f4f-6f4b-468f-9819-e8c00d3e210d)

![image](https://github.com/botbahlul/java-vosk-livesubtitle/assets/88623122/54029e86-b989-4f05-ad34-5e6f9229e76c)

another thing, have you installed Virtual Audio Cable and set it up correctly?

**Comment by ghost** [comment]
I see, i may have downloaded the wrong version as i did not have the models initially, i will try downloading it and see again.
and yes i have installed virtual Audio Cable and setted it up correctly.

**Comment by botbahlul** [comment]
You're right, maybe you've downloaded the release before I fixed some bugs  and uploaded it again without mark it as a new version.
I'm sorry for that 😂
Since the beginning my intention was only released one version for java platform. It's for learning purpose only.
